### ISSUE TITLE
Forward images from iMessage->Matrix

### ISSUE THREAD

**Issue by kfatehi** [kfatehi/matrix-puppet-imessage#11]
Currently we forward that there is "1 attachment"

We already have the filepath to the image at that point, we just need to implement and use a base method that will upload an image-type message from the point of view of the ghost user.

Once this is done, there will be a deduplication issue to deal with ... we can't "tag" images the way we can text... But we can cross that road when we get there. I think @AndrewJDR had some kind of solution to this, but I can't remember what it was.

**Comment by AndrewJDR** [comment]
My potential solution for reference:
![img_3601](https://cloud.githubusercontent.com/assets/1588857/23827728/d6c17102-066e-11e7-8941-5e19232b3bf4.PNG)

**Comment by kfatehi** [comment]
sounds good Andy. yeah i thnk we can do that.. i will try to implement this tomorrow morning... i just need to call this: https://github.com/matrix-org/matrix-js-sdk/blob/master/src/client.js#L1092

**Comment by kfatehi** [comment]
i could not figure a way to send a caption through with the applescript. always shows up as null

**Comment by kfatehi** [comment]
done
