### ISSUE TITLE
System Integrity Protection has to be turned off when running the bridge on >= macOS 10.14

### ISSUE THREAD

**Issue by michaelnew** [kfatehi/matrix-puppet-imessage#20]
There was some discussion around this in #matrix-puppet-bridge:matrix.org on 3-29-2019, and I want to put it here so it doesn't get lost. Starting in Mojave you can't watch for file changes in `~/Library/Messages` (trying to do `ls` in that directory fails, for example), so for the bridge to work you have to turn off SIP. 

To turn it off, you have to reboot into recovery mode (hold down `CMD`-`R`), open Terminal from the Utilities menu, and then `csrutil disable`. It's also an option that can be set from the boot menu in Clover when running macOS in a VM.

Obviously it would be nice to *not* have to turn off SIP, but I can't think of any way to get around it. Ultimately we want to watch for file changes and SIP doesn't let you.

I think we should put something in the readme for now.

**Comment by tdeebswihart** [comment]
You should be able to if you give the program binary Full Disk Access (in system prefs → security): I was able to do this for iTerm to debug some iMessage tools I'm building.

**Comment by michaelnew** [comment]
@chronoslynx Oh interesting. That would be a much better solution.

**Comment by nr23730** [comment]
I tried it and it's working.

**Comment by michaelnew** [comment]
I'll go ahead and close this since we have a reasonable solution now that's made it into the readme.
